#!/bin/sh
compton -b &
pulseaudio --start &
start-x11-pulseaudio &
xbanish &
xrdb ~/.config/Xresources &
xset s off &
xset -dpms &
urxvtd &
sleep 0.1 &&
startplumb &
toggletouchpad &
a &
udiskie -a -n &
dunst &
xss-lock sxlock &
autorandr horizontal &&
xwallpaper $(cat $HOME/.config/wallpaper) &&
pokoy -r &
exec dbus-launch --exit-with-session spectrwm