#!/bin/sh
compton -b &
pulseaudio --start &
start-x11-pulseaudio &
xbanish &
xrdb ~/.config/Xresources &
xset s off &
xset -dpms &
urxvtd &
mopidy &
sleep 0.1 &&
startplumb &
toggletouchpad &
a &
udiskie -a -n &
dunst &
xss-lock sxlock &
autorandr horizontal &&
xwallpaper $(cat $HOME/.config/wallpaper) &&
pokoy -r &
pidof gpg-agent >/dev/null || gpg-agent --daemon --enable-ssh-support > ~/.config/sh/zsh-ssh &
exec dbus-launch --exit-with-session spectrwm