#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
hsetroot -cover $HOME/.wallpaper &
bspc monitor -d web term bookz videos acme vidya

bspc config border_width         3
bspc config window_gap          10
bspc config focus_follows_pointer   true
bspc config click_to_focus any
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle		true
bspc config top_padding 14
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv desktop='^4'
bspc rule -a Links desktop='^1'
bspc rule -a IceCat desktop='^1'
bspc rule -a acme desktop='^5'
bspc rule -a st desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a scratchpad sticky=on state=floating hidden=on
bspc rule -a Xmessage state=floating
bspc rule -a tabbed:Links desktop='^1'
bspc rule -a lemonbar sticky=on manage=off lower=on layer=below
bspc config normal_border_color "#000000"
bspc config active_border_color "#eaffff"
bspc config focused_border_color "#9eeeee"
a &
barz &
tray &
sleep 2 && 
xdo above -t $(xdo id -n root) $(xdo id -n lemonbar) &&
xdo above -t $(xdo id -n root) $(xdo id -n panel) && 
xdo below -t $(xdo id -n panel) $(xdo id -n lemonbar)