#!/bin/sh
# DESC: Elvi to search SNPedia
# elvis: crossref         -- Search search crossref
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
    Search UESP
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://search.crossref.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://search.crossref.org/?q=${escaped_args}"
fi
