#!/bin/sh
compton -b &
xbanish &
xrdb ~/.config/Xresources &
xset s off &
xset -dpms &
sleep 0.1 &&
startplumb &
xmodmap ~/.config/Xmodmap &
toggletouchpad &
a &
dunst &
redshift -l 52:16 &
autorandr horizontal &&
xwallpaper $(cat $HOME/.config/wallpaper) &&
pokoy -r &
dbus-launch --exit-with-session spectrwm