#!/bin/sh
compton -b &
xbanish &
xwallpaper --zoom "$(cat ~/.config/wallpaper)" &
xrdb ~/.config/Xresources &
xset s off &
xset -dpms &
sleep 0.1 &&
startplumb &
xmodmap ~/.config/Xmodmap &
toggletouchpad &
a &
st &
dunst &
redshift -l 52:16 &
dbus-launch --exit-with-session spectrwm
