#!/bin/dash
export SHELL="/bin/rc"
export acmeshell="/bin/rc"
export BROWSER=firefox
export TERM=st
if [ "$(pgrep plumber)" ]; then
    echo plumber is running
else
    echo starting plumber
    plumber
fi
acme_bin_dir=$( cd $(dirname $0) && pwd )
acme -a -f /mnt/font/Monaco/10a/font $1

