#!/bin/dash
export SHELL="/bin/ksh"
export acmeshell="/bin/ksh"
export TERM=st
export PAGER='nobs'
mkdir -p /tmp/mnt/acme
if [ "$(pgrep plumber)" ]; then
    echo plumber is running
else
    echo starting plumber
    plumber
fi
acme_bin_dir=$( cd $(dirname $0) && pwd )
acme -a -f /mnt/font/Monaco/10a/font $1 &
sleep 1
9pfuse `namespace`/acme /tmp/mnt/acme
