#!/bin/sh
export ENV="$XDG_CONFIG_HOME/sh/kshrc"
export SHELL="/bin/ksh"
export acmeshell="/bin/ksh"
export TERM=dumb
export PAGER='nobs'
mkdir -p /tmp/mnt/acme
if [ "$(pgrep plumber)" ]; then
    echo plumber is running
else
    echo starting plumber
    plumber
fi
acme_bin_dir=$( cd $(dirname $0) && pwd )
acme -a -F '/mnt/font/Liberation Serif/10a/font' -f "$font" "$@" &
sleep 1
9pfuse `namespace`/acme /tmp/mnt/acme
