#!/bin/sh
url="$1"

regexmatch(){
	printf '%s' "$1" | grep -E -q "$2"
}

url=${url%$'\r'}
until regexmatch "$url" 'bloomberg\.com'; do
	url=$(curl -I "$url" | awk '/Location/{print $2}')
	url=${url%$'\r'}
done

article=$(mktemp --suffix='.html')
json=$(curl "https://outlineapi.com/parse_article?source_url=$url")

{ echo '<title>'; ( echo $json | jq -r '.["data"].title' ); echo '</title>'; ( echo $json | jq -r '.["data"].html' ) } >> $article 
echo $article
