#!/bin/sh
# runs browser with surfraw url through dmenu so one can choose
# can have multiple prefixes for choice of browser or surfraw
# function

PATH=/usr/share/surfraw:${HOME}/.config/surfraw/elvi:${PATH}

BROWSER=glinks
MARKFILE="$HOME/.bmarks"
setbrowser() { BROWSER=$1; url=$(echo "$url" | cut -c 4-); }

sort|$HOME/bin/dmenu.sh -l 10 -p 'link:' <$MARKFILE | while read url; do
[ ! "$url" ] && exit

case "$(echo $url|cut -d " " -f1)" in
    sr) setbrowser surf_priv ;;
    st) setbrowser surf_tor ;;
    Sr) setbrowser surf_tabs ;;
esac

if [ -n "$(grep "$url" "$MARKFILE")" ]
then
url=$(echo $url | sed 's/.*http/http/g' ) 
fi

args=$(echo "$url" | sed -e 's/^\w* //')
case $(echo $url| cut -d " " -f1) in
    *.*|*:*|*/*)	$BROWSER "$url" ;;
    gberg|G)		gutenberg	-browser=$BROWSER $args ;;
    uesp|tes)		uesp		-browser=$BROWSER $args ;;
    ddg|D)		duckduckgo	-browser=$BROWSER $args ;;
    aw|awiki)		archwiki	-browser=$BROWSER $args ;;
    wi|wiki)		wikipedia	-browser=$BROWSER $args ;;
    imdb)		imdb		-browser=$BROWSER $args ;;
    map)		google -m	-browser=surf_tor $args ;;
#    yt|youtube) 	sputube		-browser=$BROWSER $args ;;
    yt|youtube) 	Yt 		$args ;;
    git|github)		github		-browser=$BROWSER $args ;;
    ru)			rutracker	-browser=surf_tabs $args ;;
    aarg)		aaaaarg		-browser=surf_tabs $args ;;
    gen)		libgen		-browser=$BROWSER $args ;;
    sp|S)		startpage	-browser=surf_priv $args ;;
    cr)			crossref	-browser=surf_priv $args ;;
    gr)			perseus		-browser=$BROWSER $args ;;
    *)			duckduckgo	-browser=$BROWSER $url ;;
esac &
sleep 0.1
done
