#!/bin/sh
# uses a tsv table to create nice launcher for multiple wineprefixes (does not create them)
# format of the table:
# <name_of_the_prefix>	<arch_of_the_prefix> <location/of/the/prefix> <relative/location/of/lnk/file>	<you/can/have/any/amount/of/lnk/files/you/wish>...

WINEDEBUG='-all'
wine_binary='wine'
prefix_list='/home/lich/.wineprefixes'

chosen_prefix="$(grep $(cat $prefix_list | cut -f1 | dmenu -p 'pick wineprefix:' || exit) $prefix_list)" 
binaries="$(cat $prefix_list | cut -f4- | tr '\t' '\n')"
binary_short="$(printf "$binaries\n" | sed 's,.*/,,;s/\..*//' | dmenu -l 10 -p 'pick binary')"
[ -z "$binary_short" ] && exit

binary_sel="$(printf "$binaries" | grep "$binary_short")"
WINEARCH="$(printf "$chosen_prefix" | cut -f2)"
WINEPREFIX="$(printf "$chosen_prefix" | cut -f3)"
export WINEARCH WINEPREFIX WINDEBUG
fullpath="$WINEPREFIX$binary_sel"
cd "${fullpath%/*}"
$wine_binary start "${fullpath##*/}"

