#!/bin/mksh
export NQDIR=/tmp/nq
mkdir -p /tmp/nq
BROWSER=glinks
url=$1
ext=`echo $1 | sed 's/^\(.*\)\.\([^.]*\)/\2/'`
mpvfiles="mkv mp4 gif webm"
fehfiles="png jpg jpeg jpe"
wgetfiles="mp3 flac opus mp3?source=feed pdf"
if echo $fehfiles | egrep -w $ext > /dev/null; then
        tmp=$(mktemp)
        curl -H 'User-Agent:' "$url" > "$tmp"
        test -f "$tmp" && sxiv "$tmp"
        rm -f "$tmp"
elif echo $mpvfiles | egrep -w $ext > /dev/null; then
    mpv --loop --quiet "$1" > /dev/null &
elif echo $wgetfiles | egrep -w $ext > /dev/null; then
    wget "$1" >/dev/null &
else
    if echo $url | egrep -q "https://www.youtube.com"* ; then
        mpv --quiet "$1" >/dev/null &
        youtube-dl --get-description $url > /tmp/desc.txt &&
        most /tmp/desc.txt
    else
        $BROWSER $url 2>/dev/null &
    fi
fi
