#!/bin/sh
#sfeed_update &&
#tscrape_update &&
{ sfeed_acme $HOME/.sfeed/feeds/* | 9 awk '/^N/{print;getline;print}'; tscrape_plain $HOME/.tscrape/feeds/* | grep '^N'; } | plumb -i -d edit -a 'action=showdata filename=/news/fresh/'$(date +'%H%M%S')
