#!/bin/sh
gopher_location="/var/gopher/~lich/musings/"
html_location="/home/lich/public_html/musings/"
server="dataswamp"
page="dataswamp.org"
html_processor="pandoc"

htmlgen() {
	printf "<!DOCTYPE html><html lang=\"en\">\n<head><meta charset=\"utf-8\">\n"
	printf "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
	printf "<title>%s</title>\n" "$(sed -n "3p" $1)"
	printf "<style>\n	body{\n		margin:1em auto;\n		background-color:#ffffea;\n		max-width:50em;\n		padding:0 .62em;\n		font:1.2em/1.6 serif;\n	}\n	hr{\n	border: 0;\n		border-bottom: 3px solid #aaa;\n		height: 3px;\n}\nh1 {\n		line-height:1.2;\n	}\n	@media print{\n		body{\n			max-width:none\n		}\n	}\n</style>\n</head>\n<body>\n<article>\n"
printf "<p><small><em>%s</em></small></p>" "$(date -d$2 -R)"
	sed -n '3,$p' $1 | $html_processor
	printf "</article></body></html>"
}

htmlnew() {
	{
	printf "/tbody\na\n"
	printf "<tr><td><a href=\"%s\">%s</a></td></tr>\n.\nw\n" "$1" "$2"
	} | ssh $server ed -s $html_location/index.html
}

atomnew() {
  {
  printf "10\n"
  printf "i\n\n\t<entry>\n"
  printf "\t\t<id>%s</id>\n" "$2"
  printf "\t\t<title><![CDATA[%s]]></title>\n" "$1"
  printf "\t\t<link href=\"%s\" />\n" "$2"
  printf "\t\t<content type=\"text\"><![CDATA["
  cat "$3"
  printf "]]></content>\n"
  printf "\t\t<updated>%s</updated>\n" "$4"
  printf "\t</entry>\n.\nw\n" 
  } | ssh $server ed -s "$5"
}

gophernew() {
  { 
  printf "/MUSINGS\n+2\n"
  printf "i\n[0|%s|%s|%s|70]\n.\nw\n" "$1" "$2" "$3" 
  } | ssh $server ed -s "$gopher_location/../index.gph"
}

post() {
	date="$(sed '1 s/# //;q' $1)"
	title="$(sed '3q;d' $1)"
	ssh -q $server [[ -f $gopher_location/$1 ]] && echo "this post exists!" && exit 1
	htmlgen $1 $date | ssh $server "cat > $html_location/${1%md}html"
	scp "$1" "$server:$gopher_location/$1"
	gophernew "$title" "/~lich/musings/$1" "$page"
	atomnew "$title" "gopher://$server.org/0/~lich/musings/$1" "$1" "$date" "$gopher_location/../musings.atom.xml"
	htmlnew "$title" "${1%md}html"
	atomnew "$title" "https://dataswamp.org/~lich/musings/${1%md}html" "$date" "$html_location/musings.atom.xml"
	}

atom_rev() {
	printf "/%s\n" "${1%md}"
	printf "+3\n"
	printf ".,+%sd\n" "$(ssh $server cat $gopher_location/$1 | wc -l)"
	printf "i\n"
	printf "\t\t<content type="text"><![CDATA["
	cat "$1"
	printf "]]></content>\n.\n\n"
	printf "d\n"
	printf "i\n"
	printf "\t\t<updated>%s</updated>\n.\nw\n" "$date"
}

revise() {
	date="$(date -Iseconds)"
	atom_rev "$1" | ssh $server ed -s "$gopher_location/../musings.atom.xml"
	atom_rev "$1" | ssh $server ed -s "$html_location/musings.atom.xml"
	scp "$1" "$server:$gopher_location/$1"
	htmlgen "$1" "$date" | ssh $server "cat > $html_location/${1%md}html"
}

case "$1" in 
	n*) post "$2" ;;
	r*) revise "$2" ;;
esac
