#!/bin/sh
directory="$HOME/pictures/screenshots/$(date +%Y)/$(date +%m)/$(date +%d)"
filename="$directory/$(date +%H:%M:%S.%s).png"
command="xscreenshot"
for arg; do
case $arg in
	-s) command="xscreenshot | ff-crop $(slop -f '%x %y %w %h')" ;;
	-w) command="xscreenshot $(xdotool getmouselocation --shell | sed -n 's/WINDOW=//gp')" ;;
	-u) upload=true ;;
esac
done
mkdir -p $directory
eval "$command | ff2png > $filename"
if [ "$upload" = true ]; then
    url="$(curl --proxy 'socks5h://localhost:9050/' -sL -F files[]=@$filename https://file0.s3kr.it/upload | sed -n 's@.*https*://file0.s3kr.it/@https://file0.s3kr.it/@;s@'\'')">@@p')"
    printf "$url" | xsel -bpsi
    exiftool -overwrite_original -url=$url $filename
    xmessage -timeout 5 "$filename -> $url."
fi
